# Generated by service-limiter: Job Object limits for service '{service}'
# Run as Administrator (elevated). Requires Windows 8 or newer.
$ErrorActionPreference = 'Stop'

Add-Type -TypeDefinition @"
using System;
using System.ComponentModel;
using System.Runtime.InteropServices;
public static class SLJob {
    [StructLayout(LayoutKind.Sequential)]
    public struct IO_COUNTERS {
        public ulong ReadOperationCount, WriteOperationCount, OtherOperationCount;
        public ulong ReadTransferCount, WriteTransferCount, OtherTransferCount;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct JOBOBJECT_BASIC_LIMIT_INFORMATION {
        public long PerProcessUserTimeLimit, PerJobUserTimeLimit;
        public uint LimitFlags;
        public UIntPtr MinimumWorkingSetSize, MaximumWorkingSetSize;
        public uint ActiveProcessLimit;
        public UIntPtr Affinity;
        public uint PriorityClass, SchedulingClass;
        public uint CpuRate;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct JOBOBJECT_EXTENDED_LIMIT_INFORMATION {
        public JOBOBJECT_BASIC_LIMIT_INFORMATION BasicLimitInformation;
        public IO_COUNTERS IoInfo;
        public UIntPtr ProcessMemoryLimit, JobMemoryLimit, PeakProcessMemoryUsed, PeakJobMemoryUsed;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct JOBOBJECT_CPU_RATE_CONTROL_INFORMATION {
        public uint ControlFlags;
        public uint CpuRate;
        public ushort Weight;
        public ushort Reserved1;
        public uint Reserved2;
        public ulong ProcessTimeLimit;
        public ulong JobTimeLimit;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct JOBOBJECT_IO_RATE_CONTROL_INFORMATION {
        public long MaxIops;
        public long MaxBandwidth;
        public long ReservationIops;
        public IntPtr VolumeName;
        public uint BaseIoSize;
        public uint ControlFlags;
    }

    [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    public static extern IntPtr CreateJobObject(IntPtr attrs, string name);
    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern bool SetInformationJobObject(IntPtr job, int cls, IntPtr info, uint len);
    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern bool AssignProcessToJobObject(IntPtr job, IntPtr process);
    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern IntPtr OpenProcess(uint access, bool inherit, uint pid);
}
"@

$svc = Get-CimInstance Win32_Service -Filter "Name='{service}'"
if (-not $svc) { Write-Error "Service '{service}' not found"; exit 1 }
if ($svc.ProcessId -eq 0) { Write-Error "Service '{service}' is not running"; exit 1 }

$job = [SLJob]::CreateJobObject([IntPtr]::Zero, $null)
if ($job -eq [IntPtr]::Zero) { throw "CreateJobObject failed: $([Runtime.InteropServices.Marshal]::GetLastWin32Error())" }

# --- Memory + CPU rate, via JOBOBJECT_EXTENDED_LIMIT_INFORMATION (class 9) ---
# Correct constant: JOB_OBJECT_LIMIT_JOB_MEMORY = 0x00000200.
# (0x20 is PRIORITY_CLASS, 0x400 is DIE_ON_UNHANDLED_EXCEPTION; neither limits memory.)
$JOB_OBJECT_LIMIT_JOB_MEMORY = 0x00000200

$info = New-Object SLJob+JOBOBJECT_EXTENDED_LIMIT_INFORMATION
$info.BasicLimitInformation.LimitFlags = $JOB_OBJECT_LIMIT_JOB_MEMORY
$info.JobMemoryLimit = [UIntPtr]{mem_bytes}

$len = [Runtime.InteropServices.Marshal]::SizeOf($info)
$ptr = [Runtime.InteropServices.Marshal]::AllocHGlobal($len)
try {
    [Runtime.InteropServices.Marshal]::StructureToPtr($info, $ptr, $false)
    if (-not [SLJob]::SetInformationJobObject($job, 9, $ptr, $len)) {
        throw "SetInformationJobObject(failed, memory): $([Runtime.InteropServices.Marshal]::GetLastWin32Error())"
    }
} finally {
    [Runtime.InteropServices.Marshal]::FreeHGlobal($ptr)
}

# --- CPU rate, via JOBOBJECT_CPU_RATE_CONTROL_INFORMATION (class 15) ---
# CpuRate is in 1/10000 of a CPU; JOB_OBJECT_CPU_RATE_CONTROL_ENABLE = 0x1.
$cpu = New-Object SLJob+JOBOBJECT_CPU_RATE_CONTROL_INFORMATION
$cpu.ControlFlags = 0x1
$cpu.CpuRate = {cpu_rate}

$cLen = [Runtime.InteropServices.Marshal]::SizeOf($cpu)
$cPtr = [Runtime.InteropServices.Marshal]::AllocHGlobal($cLen)
try {
    [Runtime.InteropServices.Marshal]::StructureToPtr($cpu, $cPtr, $false)
    if (-not [SLJob]::SetInformationJobObject($job, 15, $cPtr, $cLen)) {
        Write-Warning "CPU rate limit not applied: $([Runtime.InteropServices.Marshal]::GetLastWin32Error())"
    }
} finally {
    [Runtime.InteropServices.Marshal]::FreeHGlobal($cPtr)
}

# --- I/O bandwidth, via JOBOBJECT_IO_RATE_CONTROL_INFORMATION (class 10) ---
# I/O limits must NOT go into IO_COUNTERS: those are read-only accounting
# counters, so writing them is a silent no-op.
$io = New-Object SLJob+JOBOBJECT_IO_RATE_CONTROL_INFORMATION
$io.ControlFlags = 0x1          # JOB_OBJECT_IO_RATE_CONTROL_ENABLE
$io.MaxBandwidth = {read_bytes}
$io.VolumeName = [IntPtr]::Zero
$io.BaseIoSize = 0

$iLen = [Runtime.InteropServices.Marshal]::SizeOf($io)
$iPtr = [Runtime.InteropServices.Marshal]::AllocHGlobal($iLen)
try {
    [Runtime.InteropServices.Marshal]::StructureToPtr($io, $iPtr, $false)
    if (-not [SLJob]::SetInformationJobObject($job, 10, $iPtr, $iLen)) {
        Write-Warning "I/O bandwidth limit not applied: $([Runtime.InteropServices.Marshal]::GetLastWin32Error())"
    }
} finally {
    [Runtime.InteropServices.Marshal]::FreeHGlobal($iPtr)
}

$PROCESS_QUERY_SET_INFORMATION = 0x0400
$PROCESS_TERMINATE = 0x0001
$h = [SLJob]::OpenProcess($PROCESS_QUERY_SET_INFORMATION -bor $PROCESS_TERMINATE, $false, $svc.ProcessId)
if ($h -eq [IntPtr]::Zero) { throw "OpenProcess failed: $([Runtime.InteropServices.Marshal]::GetLastWin32Error())" }
if (-not [SLJob]::AssignProcessToJobObject($job, $h)) {
    Write-Warning "AssignProcessToJobObject failed: $([Runtime.InteropServices.Marshal]::GetLastWin32Error())"
    Write-Warning "The service may already run inside a job object (common under IIS or a service host)."
    exit 2
}

Write-Output "Applied memory={mem_bytes}B cpu_rate={cpu_rate} io={read_bytes}B/s to PID $($svc.ProcessId)"
Write-Warning "Job Object limits LAPSE when this script exits and the job handle closes."
Write-Warning "For durable limits, keep service-limiter running with --durable."
